# Generated by Django 4.2.23 on 2025-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('android_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=16)),
                ('sim_cards', models.JSONField()),
                ('message_snapshot', models.JSONField(unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
