# Generated by Django 4.2.23 on 2025-08-13 05:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Username must contain atleast 5 characters.')])),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('client_number', models.CharField(max_length=16, unique=True)),
                ('secret_question', models.JSONField()),
                ('password', models.BinaryField()),
                ('client_history', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_auth.user')),
            ],
        ),
    ]
